spring:
  application:
    name: notification-service

  messages:
    basename: lang/messages,config.i18n.messages
    fallback-to-system-locale: false
    encoding: UTF-8
    cache-duration: 5

# Mail properties
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 1606e8202983e6
    password: 4279cf74784175
    protocol: smtp

# Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema:
          registry:
            url: http://localhost:8085
        specific:
          avro:
            reader: true

# Mail Information
mail:
  sender:
    email: "venomshop@email.com"
    signature: Venom Shop

server:
  port: 8083