spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: mysql
  # To do all the migration using flyway
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
inventory:
  url: "http://localhost:8082"