spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/inventory_service
    username: root
    password: mysql
  # To do all the migration using flyway
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8082